language: c

addons:
    apt:
        packages:
            - python3
            - python3-cffi

compiler:
    - gcc

script:
    - make test

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
