sudo:
    required

language: c

compiler:
    - gcc

before_install:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 50
    - pip install --user codecov
    - pip install --user cffi

script:
    - make test

after_success:
    - codecov

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
notifications:
    email: false
