language: c

compiler:
    - gcc

install:
    - export CC="gcc-5"
    - pip install --user cffi

script:
    - make test

after_success:
    - bash <(curl -s https://codecov.io/bash)

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
notifications:
    email: false
