language: c

compiler:
    - gcc

before_install:
    - pip install --user codecov
    - pip install --user cffi

before_script:
    - export CC="gcc-5"

script:
    - make test

after_success:
    - codecov --gcov-exec gcov-5

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
notifications:
    email: false
